### PR TITLE
fix: to raise error in multiple constructors

### PR DESCRIPTION
**Pull request by ota-meshi**
This PR fixes the parser to raise a syntax error when a class has multiple constructors.
However, the constructor signature handles it so that no error occurs.

### CODE REVIEW

**Comment by TyrealHu** [comment]
It seems to be right if u have multiple `constructor` in class structure.
```
class A {
    constructor(name: string)
    constructor(name: number)
    constructor(name: number | string) {}
}
```

**Comment by ota-meshi** [comment]
Yeah, I checked it with `element.value.type === 'FunctionExpression'`.

https://github.com/TyrealHu/acorn-typescript/pull/22/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R5028

**Comment by TyrealHu** [comment]
Yeah, I notice that. I have given acorn some PRs. acorn will change `this.raise('Duplicate constructor xxx')` to `this.raiseRecoverable('Duplicate constructor xxx')`. So we just need to rewrite `raiseRecoverable` method in the future. MB this pr will be useless indeed.

**Comment by ota-meshi** [comment]
> MB this pr will be useless indeed.

Sorry, I didn't quite understand. Maybe it's because I'm not good at English.
Are you saying duplicate constructors shouldn't be an error?

It seems that duplicate constructors should be an error in the test262 test case.
https://github.com/tc39/test262/blob/main/test/language/statements/class/elements/syntax/early-errors/grammar-class-body-ctor-duplicate.js

Also, TypeScript will throw an error with duplicate constructors.
https://www.typescriptlang.org/play?#code/MYGwhgzhAEDC0G8CwAoa7rAPYDsIBcAnAV2Hy0IAoBKRAX1Q01wJLIpvtTqA

> So we just need to rewrite raiseRecoverable method in the future.

How do you plan to rewrite `raiseRecoverable`? Since it only has a position and a message text, I find it difficult to handle it accurately.

**Comment by TyrealHu** [comment]
I got your point. You mean that this pr is for duplicate FunctionExpression, not the declare method.

**Pull request merged**
